# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movie_actors', through='rest_movies.Role', to='rest_movies.Person'),
        ),
        migrations.AlterField(
            model_name='role',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movie_movie', to='rest_movies.Movie'),
        ),
        migrations.AlterField(
            model_name='role',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movie_person', to='rest_movies.Person'),
        ),
    ]
